### ISSUE TITLE
The local H2O instance

### ISSUE THREAD

**Issue by Evizero** [randyzwitch/H2O.jl#3]
One obstacle I see in a native Julia implementation is firing up a local instance, which is something the R package can do.

Is this something we want to do, or do we assume the user has to fire up the H2O jar file separately?

**Comment by randyzwitch** [comment]
That's the reason why I used PyCall, so that I didn't have to worry about that right now. Conceptually, it's not that difficult, we just need to check if `localhost:54321` responds, and if not, shell out to start the .jar.

Right now, the `H2O.init()` function will start a local instance, and connect to a remote Hadoop instance.

**Comment by randyzwitch** [comment]
Okay, I removed PyCall from the code. If you call `H2O.init()`, it will do nothing other than set global variables for ip and port. I made these global, because we'll need them for each API call.

Closing this up, since we'll just start instances externally by convention.
